### ISSUE TITLE
Do you support oracle19C

### ISSUE THREAD

**Issue by 931708480** [erdemcer/kafka-connect-oracle#105]
ERROR Error during create record on topic test xid :32001900F48E0000 SQL·····
java.lang.NullPointerException
	at com.ecer.kafka.connect.oracle.OracleSourceConnectorUtils.createDataSchema(OracleSourceConnectorUtils.java:402)

**Comment by rtmyway** [comment]
> ERROR Error during create record on topic test xid :32001900F48E0000 SQL·····
> java.lang.NullPointerException
> at com.ecer.kafka.connect.oracle.OracleSourceConnectorUtils.createDataSchema(OracleSourceConnectorUtils.java:402)

I hava same ERROR in plugin database for oracle 19c, have you resolved this?

**Comment by cyrusmaster** [comment]
I hava same ERROR in plugin database for oracle 12c   pdb

**Comment by cyrusmaster** [comment]
> > ERROR Error during create record on topic test xid :32001900F48E0000 SQL·····
> > java.lang.NullPointerException
> > at com.ecer.kafka.connect.oracle.OracleSourceConnectorUtils.createDataSchema(OracleSourceConnectorUtils.java:402)
> 
> I hava same ERROR in plugin database for oracle 19c, have you resolved this?
I hava same ERROR in plugin database for oracle 12c pdb

**Comment by cyrusmaster** [comment]
> ERROR Error during create record on topic test xid :32001900F48E0000 SQL····· java.lang.NullPointerException at com.ecer.kafka.connect.oracle.OracleSourceConnectorUtils.createDataSchema(OracleSourceConnectorUtils.java:402)

I hava same ERROR in plugin database for oracle 12c pdb
