### ISSUE TITLE
Failed to start task oracle-logminer-connector-0

### ISSUE THREAD

**Issue by meghamauni** [erdemcer/kafka-connect-oracle#12]
Hello,
[2019-08-14 11:47:59,040] INFO TaskConfig values: 
	task.class = class com.ecer.kafka.connect.oracle.OracleSourceTask
 (org.apache.kafka.connect.runtime.TaskConfig:347)
[2019-08-14 11:47:59,043] ERROR Failed to start task oracle-logminer-connector-0 (org.apache.kafka.connect.runtime.Worker:464)
org.apache.kafka.connect.errors.ConnectException: Instantiation error
	at org.apache.kafka.connect.runtime.isolation.Plugins.newPlugin(Plugins.java:78)
	at org.apache.kafka.connect.runtime.isolation.Plugins.newTask(Plugins.java:200)
	at org.apache.kafka.connect.runtime.Worker.startTask(Worker.java:427)
	at org.apache.kafka.connect.runtime.standalone.StandaloneHerder.createConnectorTasks(StandaloneHerder.java:311)
	at org.apache.kafka.connect.runtime.standalone.StandaloneHerder.updateConnectorTasks(StandaloneHerder.java:336)
	at org.apache.kafka.connect.runtime.standalone.StandaloneHerder.putConnectorConfig(StandaloneHerder.java:214)
	at org.apache.kafka.connect.cli.ConnectStandalone.main(ConnectStandalone.java:115)
Caused by: org.apache.kafka.common.KafkaException: Could not instantiate class com.ecer.kafka.connect.oracle.OracleSourceTask
	at org.apache.kafka.common.utils.Utils.newInstance(Utils.java:325)
	at org.apache.kafka.connect.runtime.isolation.Plugins.newPlugin(Plugins.java:76)
	... 6 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.kafka.common.utils.Utils.newInstance(Utils.java:321)
	... 7 more
Caused by: java.lang.IllegalStateException: Cannot initialize kafka-connect-oracle SQL resources
	at com.ecer.kafka.connect.oracle.ConnectorSQL.<init>(ConnectorSQL.java:56)
	at com.ecer.kafka.connect.oracle.OracleSourceTask.<init>(OracleSourceTask.java:80)
	... 12 more
Caused by: java.lang.NullPointerException
	at com.ecer.kafka.connect.oracle.ConnectorSQL.<init>(ConnectorSQL.java:42)
	... 13 more
[2019-08-14 11:47:59,047] INFO Created connector oracle-logminer-connector (org.apache.kafka.connect.cli.ConnectStandalone:112)

How to solve this issue??

**Comment by kondasanthosh** [comment]
Hi,
am also facing same issue , did that issue resolved for you.

**Comment by liuge36** [comment]
你好 请问你解决这个问题了吗  我也遇到了同样的问题...

**Comment by erdemcer** [comment]
Hi,
Same issue solved after settting CLASSPATH showing connector . Could you please check ?
Thanks.
