### ISSUE TITLE
ORA-01300: writable database required for specified LogMiner

### ISSUE THREAD

**Issue by cfuentesgithub** [erdemcer/kafka-connect-oracle#13]
I'm getting this error, when I try to connect to a read only database (Stand by Oracle DB), do you if there any configuration to solve this issue?

ERROR Task oracle-logminer-connector-0 threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:141)
org.apache.kafka.connect.errors.ConnectException: Error at database tier, Please check : java.sql.SQLException: ORA-01300: writable database required for specified LogMiner options
ORA-06512: at "SYS.DBMS_LOGMNR", line 58
ORA-06512: at line 2

        at com.ecer.kafka.connect.oracle.OracleSourceTask.start(OracleSourceTask.java:158)
        at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:141)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:139)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:182)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by cfuentesgithub** [comment]
I realized that the error is in this sql statement execution

begin
DBMS_LOGMNR.START_LOGMNR(STARTSCN => ?,OPTIONS =>  DBMS_LOGMNR.SKIP_CORRUPTION+DBMS_LOGMNR.NO_SQL_DELIMITER+DBMS_LOGMNR.NO_ROWID_IN_STMT+DBMS_LOGMNR.DICT_FROM_ONLINE_CATALOG + DBMS_LOGMNR.CONTINUOUS_MINE+DBMS_LOGMNR.COMMITTED_DATA_ONLY+dbms_logmnr.STRING_LITERALS_IN_STMT)
; end;

**Comment by swalk123** [comment]
Hi,
am also facing same issue , did that issue resolved for you.

**Comment by cfuentesgithub** [comment]
In my case the solution was to use another DB, because in that case i tried to use a standby oracle database which was in read only mode.

**Comment by erdemcer** [comment]
Hi,
Logminer dictionary requires write access to database. On read only mode standby databases logminer can not be executed except flat file configuration for logminer dictionary. 
But this connector does not support flat file configuration.
Thanks.
