### ISSUE TITLE
source connector to Oracle stopped/failed

### ISSUE THREAD

**Issue by lkha2000** [erdemcer/kafka-connect-oracle#17]
I am new to the Kafka.  I have downloaded the **community version** of oracle connector and configured the source connector to connect to oracle database using curl. It seems to run fine if there is continuous activity.   
However, the connector would stop working after a while w/o activity.  The kafkaconfluent.log and connector status both show similar message below: 
 ERROR WorkerSourceTask{id=oracle-logminer-local-connector-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.c
onnect.runtime.WorkerTask)
org.apache.kafka.connect.errors.ConnectException: Error at database tier, Please check : java.sql.SQLTimeoutException: ORA-01013: user requested cancel of cu
rrent operation
        at com.ecer.kafka.connect.oracle.OracleSourceTask.start(OracleSourceTask.java:158)
       at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:199)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[2019-09-15 18:37:02,860] ERROR WorkerSourceTask{id=oracle-logminer-local-connector-0} Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask)

One of the logs would also indicate Out-of-process-memory on the database.  I have already increased the pga_aggregate_target size but the same error would appear after a period of time (may be longer.)  There are not much activity in the test database yet.

Can anyone help on this issue?

**Comment by lkha2000** [comment]
Part of the Issue was resolved.  However, I still received messages in the log showing "ERROR WorkerSourceTask{id=oracle-logminer-local-connector-0} Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask)"
