### ISSUE TITLE
ORA-01002: fetch out of sequence

### ISSUE THREAD

**Issue by zhouqiyue** [erdemcer/kafka-connect-oracle#18]
After started connector successfully and also can found data in Kafka topic but always report below error after ran several minutes.

java.sql.SQLException: ORA-01002: fetch out of sequence

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:450)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:399)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1059)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:522)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:257)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:587)
	at oracle.jdbc.driver.T4CCallableStatement.doOall8(T4CCallableStatement.java:220)
	at oracle.jdbc.driver.T4CCallableStatement.fetch(T4CCallableStatement.java:1061)
	at oracle.jdbc.driver.OracleStatement.fetchMoreRows(OracleStatement.java:3716)
	at oracle.jdbc.driver.InsensitiveScrollableResultSet.fetchMoreRows(InsensitiveScrollableResultSet.java:1015)
	at oracle.jdbc.driver.InsensitiveScrollableResultSet.absoluteInternal(InsensitiveScrollableResultSet.java:979)
	at oracle.jdbc.driver.InsensitiveScrollableResultSet.next(InsensitiveScrollableResultSet.java:579)
	at com.ecer.kafka.connect.oracle.OracleSourceTask.poll(OracleSourceTask.java:191)

**Comment by zhouqiyue** [comment]
I ran connector in RAC.

**Comment by cfuentesgithub** [comment]
Somebody else have had this error, there are any solution?.

**Comment by cun123** [comment]
Hi!

Has it been solved?
