### ISSUE TITLE
After the database commits, the table or view cannot be found. What's the matter

### ISSUE THREAD

**Issue by jyt15838586105** [erdemcer/kafka-connect-oracle#19]
ERROR SQL error during poll (com.ecer.kafka.connect.oracle.OracleSourceTask:236)
java.sql.SQLSyntaxErrorException: ORA-00942: table or view does not exist
at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:450)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:399)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1059)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:522)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:257)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:587)
	at oracle.jdbc.driver.T4CCallableStatement.doOall8(T4CCallableStatement.java:220)
	at oracle.jdbc.driver.T4CCallableStatement.doOall8(T4CCallableStatement.java:48)
	at oracle.jdbc.driver.T4CCallableStatement.executeForDescribe(T4CCallableStatement.java:769)
	at oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:925)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1111)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:4798)
	at oracle.jdbc.driver.OraclePreparedStatement.executeQuery(OraclePreparedStatement.java:4845)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeQuery(OraclePreparedStatementWrapper.java:1501)
	at com.ecer.kafka.connect.oracle.OracleSourceConnectorUtils.loadTable(OracleSourceConnectorUtils.java:146)
	at com.ecer.kafka.connect.oracle.OracleSourceConnectorUtils.createDataSchema(OracleSourceConnectorUtils.java:309)
	at com.ecer.kafka.connect.oracle.OracleSourceTask.poll(OracleSourceTask.java:228)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.poll(WorkerSourceTask.java:245)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:221)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by jyt15838586105** [comment]
![image](https://user-images.githubusercontent.com/39107331/68755223-1d28a580-0643-11ea-8abb-530747032878.png)

**Comment by jyt15838586105** [comment]
![Uploading image.png…]()

**Comment by erdemcer** [comment]
Hi,
is there any problem ? issue has been closed.
Thanks
