### ISSUE TITLE
org.apache.kafka.connect.errors.ConnectException: Error at database tier

### ISSUE THREAD

**Issue by swalk123** [erdemcer/kafka-connect-oracle#21]
ERROR WorkerSourceTask{id=oracle-logminer-connector-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:177)
org.apache.kafka.connect.errors.ConnectException: Error at database tier, Please check : java.sql.SQLException: ORA-00604: error occurred at recursive SQL level 1
ORA-06550: line 1, column 132:
PLS-00905: object SYS.LOGMNR_KRVRDLUID3 is invalid
ORA-06550: line 1, column 128:
PL/SQL: Statement ignored
ORA-06512: at "SYS.DBMS_LOGMNR", line 58
ORA-06512: at line 2

        at com.ecer.kafka.connect.oracle.OracleSourceTask.start(OracleSourceTask.java:182)
        at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:199)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by erdemcer** [comment]
Hi,
This error is related with invalid logminer objects not connector.  You have to recreate logminer objects or compile them .Do you have support account for Oracle ? You can find enough information to solve this issue. 
Thanks.

**Comment by swalk123** [comment]
@erdemcer  
 after recompile logmnr package ,the problem is solved. tks.
