### ISSUE TITLE
problem parsing timestamp ?

### ISSUE THREAD

**Issue by andrew6071** [erdemcer/kafka-connect-oracle#23]
Hi,

I've got a sql insert that has a timestamp in it, which fails with the following error

just looking at the insert statements there are a few fields that are defined as 

TIMESTAMP ' 2019-11-29 16:49:56' <-- this one should be a normal date / time

and one defined as 

TIMESTAMP ' 2019-11-29 15:49:56.277068+00:00'

Andrew

Nov 29 16:03:30 zoo2 connect-distributed[20999]: java.lang.IllegalArgumentException: Timestamp format must be yyyy-mm-dd hh:mm:ss[.fffffffff]
Nov 29 16:03:30 zoo2 connect-distributed[20999]:         at java.sql.Timestamp.valueOf(Timestamp.java:251)
Nov 29 16:03:30 zoo2 connect-distributed[20999]:         at com.ecer.kafka.connect.oracle.OracleSourceConnectorUtils.reSetValue(OracleSourceConnectorUtils.java:391)
Nov 29 16:03:30 zoo2 connect-distributed[20999]:         at com.ecer.kafka.connect.oracle.OracleSourceConnectorUtils.createDataSchema(OracleSourceConnectorUtils.java:343)
Nov 29 16:03:30 zoo2 connect-distributed[20999]:         at com.ecer.kafka.connect.oracle.OracleSourceTask.poll(OracleSourceTask.java:223)
Nov 29 16:03:30 zoo2 connect-distributed[20999]:         at org.apache.kafka.connect.runtime.WorkerSourceTask.poll(WorkerSourceTask.java:259)
Nov 29 16:03:30 zoo2 connect-distributed[20999]:         at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:226)
Nov 29 16:03:30 zoo2 connect-distributed[20999]:         at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:177)
Nov 29 16:03:30 zoo2 connect-distributed[20999]:         at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)
Nov 29 16:03:30 zoo2 connect-distributed[20999]:         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
Nov 29 16:03:30 zoo2 connect-distributed[20999]:         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
Nov 29 16:03:30 zoo2 connect-distributed[20999]:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
Nov 29 16:03:30 zoo2 connect-distributed[20999]:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
Nov 29 16:03:30 zoo2 connect-distributed[20999]:         at java.lang.Thread.run(Thread.java:748)

**Comment by andrew6071** [comment]
ok, i think its because the column in question is defined as a timestamp(6) with local timezone

**Comment by erdemcer** [comment]
Hi,
Let me check timestamp(X) column type parsing process on my site.
Thanks

**Comment by andrew6071** [comment]
Hi,

I've got a problem with really large numbers that are being converted as follows 8.87029777E8,

is there anyway to influence the way fields are parsed ?

Andrew

**Comment by andrew6071** [comment]
I think i've found the problem, it looks like the number is being processed as a double even though the column doesn't have a size or number of decimal places, so if i change the length of the field to the max size will that work ??

**Comment by erdemcer** [comment]
Yes, if you do not specify number field precision connector takes it float type . As you said, please specify length of the column .

**Comment by andrew6071** [comment]
Hi, just wondered if you've found the issue with the timestamps ?

**Comment by erdemcer** [comment]
Hi,
I have commited fix just now . Could you please test it ?
Thanks

**Comment by andrew6071** [comment]
I'll give it a go shortly and come back to you with the results

**Comment by andrew6071** [comment]
Hi, is there any way to change / configure the way that numbers are interpreted, the reason i ask is i can't change the length of the columns or the precision of it and they're large tables that i'm looking to consume
