### ISSUE TITLE
update error

### ISSUE THREAD

**Issue by lidongcdut** [erdemcer/kafka-connect-oracle#28]
when I update my testtable,if I dont update a not null columns ,an exception  occurred
in this table,id and name  not null. the sql is  【update TESTTABLE set ID = '0001' where ID= '0002' 】

ERROR Error during poll on topic ORCL.TEST.TESTTABLE SQL :update "TEST"."TESTTABLE" set "ID" = '0001' where "ID" = '0002' '(com.ecer.kafka.connect.oracle.OracleSourceTask:236)
org.apache.kafka.connect.errors.DataException: Invalid value: null used for required field: "NAME", schema type: INT8
	at org.apache.kafka.connect.data.ConnectSchema.validateValue(ConnectSchema.java:220)
	at org.apache.kafka.connect.data.Struct.validate(Struct.java:233)
	at org.apache.kafka.connect.data.ConnectSchema.validateValue(ConnectSchema.java:248)
	at org.apache.kafka.connect.data.Struct.put(Struct.java:216)
	at org.apache.kafka.connect.data.Struct.put(Struct.java:203)
	at com.ecer.kafka.connect.oracle.OracleSourceTask.setValueV2(OracleSourceTask.java:267)
	at com.ecer.kafka.connect.oracle.OracleSourceTask.poll(OracleSourceTask.java:224)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.poll(WorkerSourceTask.java:245)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:221)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:177)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by erdemcer** [comment]
Could you please share your test table ddl ?

**Comment by lidongcdut** [comment]
create table testtable
(
  id  varchar2(10) not null,
  name number not null
)

**Comment by erdemcer** [comment]
Did you change supplemental logging property of database ? Details are on Readme. The error seems like related with this

**Comment by lidongcdut** [comment]
alter database add supplemental log data (all) columns;
I have applyed this sql.

**Comment by lidongcdut** [comment]
thanks ，its  my fault
