### ISSUE TITLE
ORA-01292: no log file has been specified for the current LogMiner session

### ISSUE THREAD

**Issue by hdjur** [erdemcer/kafka-connect-oracle#36]
Hi,

we receive constantly at start time such errors:

    [2020-03-10 15:39:15,369] INFO Connected to database version 121020 (com.ecer.kafka.connect.oracle.OracleSourceTask:115)
    [2020-03-10 15:39:15,369] INFO Starting LogMiner Session (com.ecer.kafka.connect.oracle.OracleSourceTask:118)
    [2020-03-10 15:39:15,401] INFO Offset values , scn:2243792,commitscn:2243793,rowid:AAAW99AAFAAAACMAAC (com.ecer.kafka.connect.oracle.OracleSourceTask:139)
    [2020-03-10 15:39:15,408] INFO Captured last SCN has first position:2219344 (com.ecer.kafka.connect.oracle.OracleSourceTask:159)
    [2020-03-10 15:39:15,409] INFO Commit SCN : 2243793 (com.ecer.kafka.connect.oracle.OracleSourceTask:188)
    [2020-03-10 15:39:15,409] INFO Log Miner will start at new position SCN : 2219344 with fetch size : 1 (com.ecer.kafka.connect.oracle.OracleSourceTask:189)
    [2020-03-10 15:39:15,415] INFO WorkerSourceTask{id=oracle-logminer-connector-0} Committing offsets (org.apache.kafka.connect.runtime.WorkerSourceTask:398)
    [2020-03-10 15:39:15,415] INFO WorkerSourceTask{id=oracle-logminer-connector-0} flushing 0 outstanding messages for offset commit (org.apache.kafka.connect.runtime.WorkerSourceTask:415)
    [2020-03-10 15:39:15,416] ERROR WorkerSourceTask{id=oracle-logminer-connector-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:179)
    org.apache.kafka.connect.errors.ConnectException: Error at database tier, Please check : java.sql.SQLException: ORA-01292: no log file has been specified for the current LogMiner session
    ORA-06512: at "SYS.DBMS_LOGMNR", line 58
    ORA-06512: at line 2
    
    	at com.ecer.kafka.connect.oracle.OracleSourceTask.start(OracleSourceTask.java:220)
    	at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:199)
    	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:177)
    	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)
    	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    	at java.lang.Thread.run(Thread.java:748)
    [2020-03-10 15:39:15,420] ERROR WorkerSourceTask{id=oracle-logminer-connector-0} Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:180)
    [2020-03-10 15:39:15,420] INFO Stop called for logminer (com.ecer.kafka.connect.oracle.OracleSourceTask:294)
    [2020-03-10 15:39:15,420] INFO Logminer session cancel (com.ecer.kafka.connect.oracle.OracleSourceTask:297)
    [2020-03-10 15:39:15,420] WARN Could not stop task (org.apache.kafka.connect.runtime.WorkerSourceTask:190)
    java.lang.NullPointerException
    	at com.ecer.kafka.connect.oracle.OracleSourceTask.stop(OracleSourceTask.java:298)
    	at org.apache.kafka.connect.runtime.WorkerSourceTask.tryStop(WorkerSourceTask.java:187)
    	at org.apache.kafka.connect.runtime.WorkerSourceTask.close(WorkerSourceTask.java:151)
    	at org.apache.kafka.connect.runtime.WorkerTask.doClose(WorkerTask.java:156)
    	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:183)
    	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)
    	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    	at java.lang.Thread.run(Thread.java:748)

CDC worked for a while, and then we started archiving of the logs after 10 minutes, counting on that they will be processed during that interval, and after that, it stopped working. Now, db logs are not archived anymore, but now we cannot run the kafka connector anymore, without getting this at start time.
How to recover from this?

**Comment by hdjur** [comment]
setting:

reset.offset=true

resolves the issue

**Comment by erdemcer** [comment]
Hi,
"reset.offset = true"  resets offset value as you know , and you can not start connector from the where it left off.  Please be careful about this.
Thanks

**Comment by hdjur** [comment]
Hi, 
thanks for the update. As I approached this from kafka admin point of view, I didn't investigate much the source code. Could you please summarize in a few words how the sync between the source and target (sink) works, with respect to continuing exactly from where it left off after restart? What are the main cases covered, and how does the parameter reset.offset affects dealing with the problem, ie in which case this parameter set to false offers some benefit?

For example:
case 1: reset.offset = true, there are new Oracle logs that are not collected yet by connector (that is shipped to Kafka), and there are Oracle logs that are already collected, but not yet archived, and there are no Oracle logs that were never collected but are already archived (due to inactivity of connector, and due to log archiver that works independently of connector)

**Comment by erdemcer** [comment]
Hi,
If you start connector first time , it captures current SCN of Oracle database and begins to mine from redo and archived logs 
from this SCN. Connector works endless until stopping it by user or any failure cause.

After stopping of connector because of any reason, starting of connector firstly checks "reset.offset" parameter.If it is set true,
connector begins current SCN of database and ignores last position of where it left off.If it is not set true , connector begins
from last position of before work and continues to mine .

Connector does not look logs are archive or not. It only looks mined last SCN . After this SCN all entries are captured if "reset.offset" is false.
Thanks
