### ISSUE TITLE
when i restart my database 

### ISSUE THREAD

**Issue by lidongcdut** [erdemcer/kafka-connect-oracle#41]
the error is this：
ERROR SQL error during poll (com.ecer.kafka.connect.oracle.OracleSourceTask:277)
java.sql.SQLRecoverableException: Closed Connection: next
	at oracle.jdbc.driver.InsensitiveScrollableResultSet.next(InsensitiveScrollableResultSet.java:570)
	at com.ecer.kafka.connect.oracle.OracleSourceTask.poll(OracleSourceTask.java:227)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.poll(WorkerSourceTask.java:245)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:221)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:177)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

when my database started  ,the error is not stop

**Comment by erdemcer** [comment]
Hi,
While connector is running did you restart your database ?
Thanks

**Comment by lidongcdut** [comment]
> Hi,
> While connector is running did you restart your database ?
> Thanks
yes

**Comment by erdemcer** [comment]
Hi,
Actually , i suggest you stop connector before restart database. 
Thanks

**Comment by lidongcdut** [comment]
thinks
i just run “startup force” on my database

**Comment by erdemcer** [comment]
If connection level error occurs while connector working , the connector must be restarted after problem has been solved.If this database restart process is planned you can stop connector then start it after database has been started .

**Comment by santoshchanda01** [comment]
Hi @erdemcer 

Is there is a way to stop the connector automatically when DB connection error is encountered?
