### ISSUE TITLE
org.apache.kafka.connect.errors.ConnectException

### ISSUE THREAD

**Issue by lihdb** [erdemcer/kafka-connect-oracle#42]
ERROR Task oracle-logminer-connector-0 threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:142)
org.apache.kafka.connect.errors.ConnectException: Error at database tier, Please check : java.sql.SQLException: ORA-06550: 第 2 行, 第 251 列: 
PLS-00302: 必须声明 'STRING_LITERALS_IN_STMT' 组件
ORA-06550: 第 2 行, 第 1 列: 
PL/SQL: Statement ignored

	at com.ecer.kafka.connect.oracle.OracleSourceTask.start(OracleSourceTask.java:216)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:137)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:140)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:175)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[2020-04-08 12:56:38,808] ERROR Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:143)
[2020-04-08 12:56:41,026] INFO Reflections took 11793 ms to scan 64 urls, producing 4624 keys and 29353 values  (org.reflections.Reflections:229)

**Comment by erdemcer** [comment]
Hi,
What is your db version ?

**Comment by minisancy** [comment]
i have the same question, 
my db version is 11.1.0.7.0
