### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: 1

### ISSUE THREAD

**Issue by charliecat22** [erdemcer/kafka-connect-oracle#44]
[2020-04-09 17:39:13,599] ERROR WorkerSourceTask{id=oracle-logminer-connector-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:177)
java.lang.ArrayIndexOutOfBoundsException: 1
        at java.util.Arrays$ArrayList.get(Arrays.java:3841)
        at com.ecer.kafka.connect.oracle.OracleSourceConnectorUtils.parseTableWhiteList(OracleSourceConnectorUtils.java:134)
        at com.ecer.kafka.connect.oracle.OracleSourceConnectorUtils.<init>(OracleSourceConnectorUtils.java:92)
        at com.ecer.kafka.connect.oracle.OracleSourceTask.start(OracleSourceTask.java:113)
        at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:198)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[2020-04-09 17:39:13,601] ERROR WorkerSourceTask{id=oracle-logminer-connector-0} Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:178)
[2020-04-09 17:39:13,602] INFO Stop called for logminer (com.ecer.kafka.connect.oracle.OracleSourceTask:290)
[2020-04-09 17:39:13,602] INFO Logminer session cancel (com.ecer.kafka.connect.oracle.OracleSourceTask:293)
[2020-04-09 17:39:13,602] WARN Could not stop task (org.apache.kafka.connect.runtime.WorkerSourceTask:189)
java.lang.NullPointerException
        at com.ecer.kafka.connect.oracle.OracleSourceTask.stop(OracleSourceTask.java:294)
        at org.apache.kafka.connect.runtime.WorkerSourceTask.tryStop(WorkerSourceTask.java:186)
        at org.apache.kafka.connect.runtime.WorkerSourceTask.close(WorkerSourceTask.java:150)
        at org.apache.kafka.connect.runtime.WorkerTask.doClose(WorkerTask.java:154)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:181)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by erdemcer** [comment]
Hi
Could you please send your connector configs ?

**Comment by charliecat22** [comment]
name=oracle-logminer-connector
connector.class=com.ecer.kafka.connect.oracle.OracleSourceConnector
db.name.alias=test01
tasks.max=1
topic=cdctest
db.name=orcl.test
db.hostname=xxx.xxx.xxx.xxx
db.port=1521
db.user=test
db.user.password=test
db.fetch.size=1
table.whitelist=test_user
table.blacklist=none
parse.dml.data=true
reset.offset=true
start.scn=
multitenant=false

**Comment by erdemcer** [comment]
Some properties seem wrong. table.whitelist does not contain schema name of table . If you do not set table.blacklist leave it blank

table.whilelist=<SCHEMA_NAME>.test_user 
table.blacklist=

**Comment by charliecat22** [comment]
The issue is solved as you said. 
I have another question ：
After run connect-standalone.sh.
The topic cdctest doesn't create . I cant find it in zookeeper topic list.
How can i consumer the topic in console.

**Comment by erdemcer** [comment]
After run connector , did you execute any DML ? If you did not topic will not be created .
In order to consume records you can use ,
kafka-console-consumer --bootstrap-server `hostname`:9092 --topic cdctest

**Comment by charliecat22** [comment]
I already  excute insert  and commit . But the topic not be created.  The log :
```
[2020-04-10 14:53:44,894] INFO WorkerSourceTask{id=oracle-logminer-connector-0} Committing offsets (org.apache.kafka.connect.runtime.WorkerSourceTask:397)
[2020-04-10 14:53:44,894] INFO WorkerSourceTask{id=oracle-logminer-connector-0} flushing 0 outstanding messages for offset commit (org.apache.kafka.connect.runtime.WorkerSourceTask:414)

```
It seems not capture any change.
