### ISSUE TITLE
ERROR Plugin class loader for connector

### ISSUE THREAD

**Issue by amlen** [erdemcer/kafka-connect-oracle#45]
Hi , 

I have this error can u help me please 

 ERROR Plugin class loader for connector: 'com.ecer.kafka.connect.oracle.OracleSourceConnector' was not found. Returning: org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader@2b546384 (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader)

**Comment by erdemcer** [comment]
Hi,
To where did you copy jar file ? Does your CLASSPATH see this location ?

**Comment by amlen** [comment]
i copy  Copy kafka-connect-oracle-1.0.jar and lib/ojdbc7.jar to KAFKA_HOME/lib folder.

 Does your CLASSPATH see this location ? No

**Comment by erdemcer** [comment]
Before execution i set CLASSPATH as
export CLASSPATH=$KAFKA_HOME/share/java/kafka/:$KAFKA_HOME/share/java/kafka-connect-jdbc/

and my jar files are in $KAFKA_HOME/share/java/kafka-connect-jdbc
You are free to copy jar files to anywhere , but CLASSPATH must see this location .

**Comment by amlen** [comment]
Now i hve this error 
ERROR Stopping after connector error (org.apache.kafka.connect.cli.ConnectStandalone)
java.nio.file.NoSuchFileException: ..\..\config\OracleSourceConnector.propertieso

**Comment by erdemcer** [comment]
Is the OracleSourceConnector.propertieso file in the proper location you set while starting connector? Could you please check it ?

**Comment by amlen** [comment]
> 
> 
> Is the OracleSourceConnector.propertieso file in the proper location you set while starting connector? Could you please check it ?

sorry its  a typing error, but i still have this error  : ERROR Plugin class loader for connector: 'com.ecer.kafka.connect.oracle.OracleSourceConnector' was not found. Returning: org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader@2b546384 (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader)

**Comment by erdemcer** [comment]
Hi,
Issue can be related with following issue , Could you please check it out with your configuration ?
https://github.com/confluentinc/kafka-connect-jdbc/issues/766
Thanks

**Comment by charliecat22** [comment]
I have the same issue work with kafka_2.11-2.4.0 . 
Then I change to kafka_2.11-2.1.1 , this error not report.

**Comment by erdemcer** [comment]
Hi,
Delete all kafka-connect-oracle-1.0.jar and ojdbc7.jar jar files from directories where you copied . Then only copy these jar files to $KAFKA_HOME/share/java/kafka directory. This location is set as classpath while starting connector . Do not set any classpath variable . Then try to start . If error continues , could you please send all output ?
Thanks

**Comment by amlen** [comment]
Hi, 
I deleted all kafka-connect-oracle-1.0.jar and ojdbc7.jar jar files from directories where i copied . Then  i only copy these jar files to $KAFKA_HOME/share/java/kafka directory. 

I set  this location($KAFKA_HOME/share/java/kafka directory)  as classpath 

but i have this error :

ERROR Failed to create job for ../../config/OracleSourceConnector.properties (org.apache.kafka.connect.cli.ConnectStandalone)
[2020-04-13 15:07:35,675] ERROR Stopping after connector error (org.apache.kafka.connect.cli.ConnectStandalone)
java.util.concurrent.ExecutionException: org.apache.kafka.connect.errors.ConnectException: Failed to find any class that implements Connector and which name matches com.ecer.kafka.connect.oracle.OracleSourceConnector, available connectors are: PluginDesc{klass=class org.apache.kafka.connect.file.FileStreamSinkConnector, name='org.apache.kafka.connect.file.FileStreamSinkConnector', version='2.4.1', encodedVersion=2.4.1, type=sink, typeName='sink', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.file.FileStreamSourceConnector, name='org.apache.kafka.connect.file.FileStreamSourceConnector', version='2.4.1', encodedVersion=2.4.1, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.mirror.MirrorCheckpointConnector, name='org.apache.kafka.connect.mirror.MirrorCheckpointConnector', version='1', encodedVersion=1, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.mirror.MirrorHeartbeatConnector, name='org.apache.kafka.connect.mirror.MirrorHeartbeatConnector', version='1', encodedVersion=1, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.mirror.MirrorSourceConnector, name='org.apache.kafka.connect.mirror.MirrorSourceConnector', version='1', encodedVersion=1, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.MockConnector, name='org.apache.kafka.connect.tools.MockConnector', version='2.4.1', encodedVersion=2.4.1, type=connector, typeName='connector', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.MockSinkConnector, name='org.apache.kafka.connect.tools.MockSinkConnector', version='2.4.1', encodedVersion=2.4.1, type=sink, typeName='sink', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.MockSourceConnector, name='org.apache.kafka.connect.tools.MockSourceConnector', version='2.4.1', encodedVersion=2.4.1, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.SchemaSourceConnector, name='org.apache.kafka.connect.tools.SchemaSourceConnector', version='2.4.1', encodedVersion=2.4.1, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.VerifiableSinkConnector, name='org.apache.kafka.connect.tools.VerifiableSinkConnector', version='2.4.1', encodedVersion=2.4.1, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.VerifiableSourceConnector, name='org.apache.kafka.connect.tools.VerifiableSourceConnector', version='2.4.1', encodedVersion=2.4.1, type=source, typeName='source', location='classpath'}
        at org.apache.kafka.connect.util.ConvertingFutureCallback.result(ConvertingFutureCallback.java:115)
        at org.apache.kafka.connect.util.ConvertingFutureCallback.get(ConvertingFutureCallback.java:99)
        at org.apache.kafka.connect.cli.ConnectStandalone.main(ConnectStandalone.java:118)
Caused by: org.apache.kafka.connect.errors.ConnectException: Failed to find any class that implements Connector and which name matches com.ecer.kafka.connect.oracle.OracleSourceConnector, available connectors are: PluginDesc{klass=class org.apache.kafka.connect.file.FileStreamSinkConnector, name='org.apache.kafka.connect.file.FileStreamSinkConnector', version='2.4.1', encodedVersion=2.4.1, type=sink, typeName='sink', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.file.FileStreamSourceConnector, name='org.apache.kafka.connect.file.FileStreamSourceConnector', version='2.4.1', encodedVersion=2.4.1, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.mirror.MirrorCheckpointConnector, name='org.apache.kafka.connect.mirror.MirrorCheckpointConnector', version='1', encodedVersion=1, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.mirror.MirrorHeartbeatConnector, name='org.apache.kafka.connect.mirror.MirrorHeartbeatConnector', version='1', encodedVersion=1, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.mirror.MirrorSourceConnector, name='org.apache.kafka.connect.mirror.MirrorSourceConnector', version='1', encodedVersion=1, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.MockConnector, name='org.apache.kafka.connect.tools.MockConnector', version='2.4.1', encodedVersion=2.4.1, type=connector, typeName='connector', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.MockSinkConnector, name='org.apache.kafka.connect.tools.MockSinkConnector', version='2.4.1', encodedVersion=2.4.1, type=sink, typeName='sink', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.MockSourceConnector, name='org.apache.kafka.connect.tools.MockSourceConnector', version='2.4.1', encodedVersion=2.4.1, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.SchemaSourceConnector, name='org.apache.kafka.connect.tools.SchemaSourceConnector', version='2.4.1', encodedVersion=2.4.1, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.VerifiableSinkConnector, name='org.apache.kafka.connect.tools.VerifiableSinkConnector', version='2.4.1', encodedVersion=2.4.1, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.VerifiableSourceConnector, name='org.apache.kafka.connect.tools.VerifiableSourceConnector', version='2.4.1', encodedVersion=2.4.1, type=source, typeName='source', location='classpath'}
        at org.apache.kafka.connect.runtime.isolation.Plugins.connectorClass(Plugins.java:203)
        at org.apache.kafka.connect.runtime.isolation.Plugins.newConnector(Plugins.java:175)
        at org.apache.kafka.connect.runtime.AbstractHerder.getConnector(AbstractHerder.java:519)
        at org.apache.kafka.connect.runtime.AbstractHerder.validateConnectorConfig(AbstractHerder.java:289)
        at org.apache.kafka.connect.runtime.standalone.StandaloneHerder.putConnectorConfig(StandaloneHerder.java:194)
        at org.apache.kafka.connect.cli.ConnectStandalone.main(ConnectStandalone.java:115)

Thanks

**Comment by charliecat22** [comment]
Hi amlen,
I copy kafka-connect-oracle-1.0.jar to $KAFKA_HOME/share/java/kafka, copy ojdbc7.jar to $KAFKA_HOME/libs and edited connect-standalone.properties : plugin.path=$KAFKA_HOME/share/java/kafka.
No error report

**Comment by amlen** [comment]
> 
> 
> Hi amlen,
> I copy kafka-connect-oracle-1.0.jar to $KAFKA_HOME/share/java/kafka, copy ojdbc7.jar to $KAFKA_HOME/libs and edited connect-standalone.properties : plugin.path=$KAFKA_HOME/share/java/kafka.
> No error report

Thanks for your response , I did  all what you mentioned , but i still have this  error : ERROR Failed to start task oracle-logminer-connector-0

which path did you set in CLASSPATH  ?  $KAFKA_HOME/share/java/kafka or $KAFKA_HOME/libs ?

**Comment by charliecat22** [comment]
> > Hi amlen,
> > I copy kafka-connect-oracle-1.0.jar to $KAFKA_HOME/share/java/kafka, copy ojdbc7.jar to $KAFKA_HOME/libs and edited connect-standalone.properties : plugin.path=$KAFKA_HOME/share/java/kafka.
> > No error report
> 
> Thanks for your response , I did all what you mentioned , but i still have this error : ERROR Failed to start task oracle-logminer-connector-0
> 
> which path did you set in CLASSPATH ? $KAFKA_HOME/share/java/kafka or $KAFKA_HOME/libs ?

I set  $KAFKA_HOME/share/java/kafka in CLASSPATH

**Comment by amlen** [comment]
thanks  No error report but i have warning and no message in the topic

 The (sub)resource method createConnector in org.apache.kafka.connect.runtime.rest.resources.ConnectorsResource contains empty path annotation.
WARNING: The (sub)resource method listConnectors in org.apache.kafka.connect.runtime.rest.resources.ConnectorsResource contains empty path annotation.
WARNING: The (sub)resource method listConnectorPlugins in org.apache.kafka.connect.runtime.rest.resources.ConnectorPluginsResource contains empty path annotation.
WARNING: The (sub)resource method serverInfo in org.apache.kafka.connect.runtime.rest.resources.RootResource contains empty path annotation.

**Comment by erdemcer** [comment]
This issue is same as #43 . Is your kafka version 2.11-2.4.0 ? and if it is possible i would like to see your issue from remote ?

**Comment by amlen** [comment]
> 
> 
> This issue is same as #43 . Is your kafka version 2.11-2.4.0 ? No my kafkfka version is kafka_2.11-2.4.1


and if it is possible i would like to see your issue from remote ? yes

**Comment by erdemcer** [comment]
Hi,
Sometimes in connector config table.whitelist and table.blacklist values are written in lower case . Could you please check them ? They must be in uppercase.
Thanks

**Comment by amlen** [comment]
i set config table.whitelist and table.blacklist values in uppercase
but i still not get any data 

my config :
name=oracle-logminer-connector
connector.class=com.ecer.kafka.connect.oracle.OracleSourceConnector
db.name.alias=
tasks.max=1
topic=test
db.name=ORCL1
db.hostname=localhost
db.port=1521
db.user=userTest
db.user.password=userTest
db.fetch.size=1
table.whitelist=ORCL1.TEST
table.blacklist=ORCL1.TESTBLACK
parse.dml.data=true
reset.offset=false
multitenant=false
start.scn=
