### ISSUE TITLE
 ERROR Failed to start task oracle-logminer-connector-0 

### ISSUE THREAD

**Issue by amlen** [erdemcer/kafka-connect-oracle#46]
Hello, 

Please can you help me? i have this error : 

 ERROR Failed to start task oracle-logminer-connector-0 (org.apache.kafka.connect.runtime.Worker)
java.lang.NoClassDefFoundError: net/sf/jsqlparser/JSQLParserException
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:427)
        at org.apache.kafka.common.config.ConfigDef.parseType(ConfigDef.java:719)
        at org.apache.kafka.common.config.ConfigDef.parseValue(ConfigDef.java:474)
        at org.apache.kafka.common.config.ConfigDef.parse(ConfigDef.java:467)
        at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:108)
        at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:142)
        at org.apache.kafka.connect.runtime.TaskConfig.<init>(TaskConfig.java:51)
        at org.apache.kafka.connect.runtime.Worker.startTask(Worker.java:431)
        at org.apache.kafka.connect.runtime.standalone.StandaloneHerder.createConnectorTasks(StandaloneHerder.java:313)
        at org.apache.kafka.connect.runtime.standalone.StandaloneHerder.updateConnectorTasks(StandaloneHerder.java:338)
        at org.apache.kafka.connect.runtime.standalone.StandaloneHerder.putConnectorConfig(StandaloneHerder.java:216)
        at org.apache.kafka.connect.cli.ConnectStandalone.main(ConnectStandalone.java:115)
Caused by: java.lang.ClassNotFoundException: net.sf.jsqlparser.JSQLParserException
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:435)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
        at org.apache.kafka.connect.runtime.isolation.PluginClassLoader.loadClass(PluginClassLoader.java:104)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 13 more

**Comment by erdemcer** [comment]
This issue has been solved i think . The connector restarted but no message published ?

**Comment by amlen** [comment]
> 
> 
> This issue has been solved i think . The connector restarted but no message published ? yes
