### ISSUE TITLE
java.sql.SQLException: ORA-06550

### ISSUE THREAD

**Issue by yongorg** [erdemcer/kafka-connect-oracle#50]
hi，I have a problem！
**This is my connector configuration：**
{
connector.class: "com.ecer.kafka.connect.oracle.OracleSourceConnector",
reset.offset: "true",
db.hostname: "192.168.1.176",
tasks.max: "1",
db.user.password: "test123456",
table.blacklist: "",
table.whitelist: "TEST1.T1",
db.user: "test1",
start.scn: **"0",**
db.port: "1521",
db.fetch.size: "1",
multitenant: "false",
topic: "Increment-Source-192",
parse.dml.data: "true",
db.name: "orcl",
db.name.alias: "test",
name: "Increment-Source-192"
}
**This is the error message from my connector**
org.apache.kafka.connect.errors.ConnectException: Error at database tier, Please check : java.sql.SQLException: ORA-06550: line 2, column 54: PLS-00201: identifier 'DBMS_LOGMNR.SKIP_CORRUPTION' must be declared ORA-06550: line 2, column 1: PL/SQL: Statement ignored at com.ecer.kafka.connect.oracle.OracleSourceTask.start(OracleSourceTask.java:175) at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:199) at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:177) at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227) at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:748) 

**My Oracle database version is 10g**
How to solve it? thanks！

**Comment by yongorg** [comment]
Hi,
Is it related to the database version?Which versions of Oracle databases does it support?
Thanks!

**Comment by erdemcer** [comment]
Hi,
All versions are supported. Are you using last updated code?

**Comment by yongorg** [comment]
not yet.

**Comment by yongorg** [comment]
no,
This is still the problem with the previous version

**Comment by erdemcer** [comment]
Could you please check test1 db.user privileges mentioned in readme ? And if it is possible could you please test it with new updated code ? 
Connector tests are done from 11g to 19c. What is your db version ?

**Comment by yongorg** [comment]
10g

**Comment by erdemcer** [comment]
Exact full version ?

**Comment by erdemcer** [comment]
Hi,
I have updated code with bug fix . I do not know exact version of your database . It can give following error 
``` "component 'STRING_LITERALS_IN_STMT' must be declared" ```
Could you please check it with new code ?
Thanks

**Comment by zhouchunyan0228** [comment]
I have encounterd the same bug.
org.apache.kafka.connect.errors.ConnectException: Error at database tier, Please check : java.sql.SQLException: ORA-06550: line 2, column 283:
PLS-00302: component 'STRING_LITERALS_IN_STMT' must be declared
ORA-06550: line 2, column 1:
PL/SQL: Statement ignored

        at com.ecer.kafka.connect.oracle.OracleSourceTask.start(OracleSourceTask.java:223)
        at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:137)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:140)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:175)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by erdemcer** [comment]
Hi,
What is you db version that connector is running on ?
thanks
