### ISSUE TITLE
 Unable to initialize REST server

### ISSUE THREAD

**Issue by amlen** [erdemcer/kafka-connect-oracle#54]
Hello, 

Please can you help me i have this error : 

ERROR Stopping due to error (org.apache.kafka.connect.cli.ConnectStandalone)
org.apache.kafka.connect.errors.ConnectException: Unable to initialize REST server
        at org.apache.kafka.connect.runtime.rest.RestServer.initializeServer(RestServer.java:215)
        at org.apache.kafka.connect.cli.ConnectStandalone.main(ConnectStandalone.java:87)
Caused by: java.io.IOException: Failed to bind to 0.0.0.0/0.0.0.0:8083
        at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:346)
        at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:307)
        at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
        at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:231)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
        at org.eclipse.jetty.server.Server.doStart(Server.java:385)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
        at org.apache.kafka.connect.runtime.rest.RestServer.initializeServer(RestServer.java:213)
        ... 1 more
Caused by: java.net.BindException: Address already in use: bind
        at java.base/sun.nio.ch.Net.bind0(Native Method)
        at java.base/sun.nio.ch.Net.bind(Net.java:479)
        at java.base/sun.nio.ch.Net.bind(Net.java:468)
        at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:220)
        at java.base/sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:88)
        at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:342)
        ... 8 more

Thanks

**Comment by erdemcer** [comment]
Hi,
"Address already in use: bind" says there is open Kafka Connect worker working on this port. Could you please check it ?
Thanks

**Comment by amlen** [comment]
Hi , 
thanks for your response please how can i check it ?

**Comment by erdemcer** [comment]
Are you using confluent ? 
Could you please type "confluent status" ?

**Comment by amlen** [comment]
No i don't use confluent

**Comment by erdemcer** [comment]
Hi,
does the problem still persist ? I couldn't care for a while
Thanks

**Comment by Elhadj-Balde** [comment]
Hi @amlen ,

Please how do you solve this issues ?

Thanks!
