### ISSUE TITLE
foreign key null value error

### ISSUE THREAD

**Issue by schdai** [erdemcer/kafka-connect-oracle#56]
why? 
2020-05-12 09:45:12,629] ERROR Error during poll on topic demo SQL :update "XTHIS"."IPI_REGISTRATION" set "TOTAL_CHARGE_AMT" = 2655.28, "TOTAL_PREPAY_AMT" = 2000 where "ID" = 'e24af00b369480817db9' and "TOTAL_CHARGE_AMT" = 2655.28 and "TOTAL_PREPAY_AMT" = 2000 (com.ecer.kafka.connect.oracle.OracleSourceTask:286)
org.apache.kafka.connect.errors.DataException: Invalid value: null used for required field: "PERSON_INFO_ID", schema type: STRING
        at org.apache.kafka.connect.data.ConnectSchema.validateValue(ConnectSchema.java:220)
        at org.apache.kafka.connect.data.Struct.validate(Struct.java:233)
        at org.apache.kafka.connect.data.ConnectSchema.validateValue(ConnectSchema.java:248)
      
My Oracle is 11.2.0.4, and configuration as follows:
name=oracle-logminer-connector
connector.class=com.ecer.kafka.connect.oracle.OracleSourceConnector
db.name.alias=racdb
tasks.max=1
db.name=racdb
db.hostname=
db.port=1521
db.user=
db.user.password=
db.fetch.size=1
table.whitelist=XTHIS.TESTA,XTHIS.IPD_DOCTOR_ORDERS,XTHIS.IPI_REGISTRATION
table.blacklist=
parse.dml.data=true
reset.offset=true
start.scn=
multitenant=false
topic=demo

There is a foreign key named  PERSON_INFO_ID (not null) on table IPI_REGISTRATION .  
My application runs normally, why ?

**Comment by schdai** [comment]
if I set parse.dml.data=false, then all is ok. but json message will lose the data and before section as follows:

"payload": {
		"SCN": 14423135346110,
		"SEG_OWNER": "XTHIS",
		"TABLE_NAME": "IPD_DOCTOR_ORDERS",
		"TIMESTAMP": 1589248368000,
		"SQL_REDO": "update \"XTHIS\".\"IPD_DOCTOR_ORDERS\" set \"S_YZZT_DM\" = '30', \"STATUS_DEPT_ID\" = '9aba8b800036808126cc', \"STATUS_PERSON_ID\" = '480', \"STATUS_DATE\" = TIMESTAMP ' 2020-05-12 09:53:16' where \"ID\" = '064199b94bb58081066d' and \"S_YZZT_DM\" = '20' and \"STATUS_DEPT_ID\" = '013001120201' and \"STATUS_PERSON_ID\" = '481' and \"STATUS_DATE\" = TIMESTAMP ' 2020-05-12 08:23:07'",
		"OPERATION": "UPDATE",
		"data": null,
		"before": null
	}

**Comment by erdemcer** [comment]
Hi,
Error comes from parsing of sql statements . Because parse.dml.data is set false error does not occur. For foreign key  issue could you please check supplemantal logging property of your database ? On readme you can find detail. Not having all field of table in SQL statement you can encounter this error .

Thanks
