### ISSUE TITLE
 java.sql.SQLException: ORA-01002: fetch out of sequence

### ISSUE THREAD

**Issue by yongorg** [erdemcer/kafka-connect-oracle#60]
This connector has a serious problem.I found that it could not capture a very large amount of data.I updated a table of 3 million rows and was unable to capture it.

![image](https://user-images.githubusercontent.com/50346324/82665164-d0fb9500-9c65-11ea-99fe-610447513f31.png)

[2020-05-22 19:42:35,668] ERROR SQL error during poll (com.ecer.kafka.connect.oracle.OracleSourceTask:281)
java.sql.SQLException: ORA-01002: fetch out of sequence

 at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:450)
 at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:399)
 at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1059)
 at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:522)
 at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:257)
 at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:587)
 at oracle.jdbc.driver.T4CCallableStatement.doOall8(T4CCallableStatement.java:220)
 at oracle.jdbc.driver.T4CCallableStatement.fetch(T4CCallableStatement.java:1061)
 at oracle.jdbc.driver.OracleStatement.fetchMoreRows(OracleStatement.java:3716)
 at oracle.jdbc.driver.InsensitiveScrollableResultSet.fetchMoreRows(InsensitiveScrollableResultSet.java:1015)
 at oracle.jdbc.driver.InsensitiveScrollableResultSet.absoluteInternal(InsensitiveScrollableResultSet.java:979)
 at oracle.jdbc.driver.InsensitiveScrollableResultSet.next(InsensitiveScrollableResultSet.java:579)
 at com.ecer.kafka.connect.oracle.OracleSourceTask.poll(OracleSourceTask.java:229)
 at org.apache.kafka.connect.runtime.WorkerSourceTask.poll(WorkerSourceTask.java:245)
 at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:221)
 at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:177)
 at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)
 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
 at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
 at java.lang.Thread.run(Thread.java:748)

**Comment by yongorg** [comment]
HI, what's the problem? Can you help me out?

**Comment by erdemcer** [comment]
Hi,
After crash or error have you restarted connector again ?

**Comment by yongorg** [comment]
Hi，
The connector still has this error after restarting.

**Comment by AvinashUrs** [comment]
Hi,
Has it been solved ? 
I'm facing the same problem

**Comment by erdemcer** [comment]
Hi,
Which jdbc driver are you using? version ? And is there any process on your db that can kill connector session which can be idle ?
Thanks

**Comment by AvinashUrs** [comment]
Hi,
It is  OJDBC7 and i suspected issue from cursors in stored procedures but after fixing it also getting same error,
i know its commit issue which is default in jdbc, can you help us out to fix the above.
Thank you.

**Comment by liujun168** [comment]
Hi,
&nbsp;&nbsp;Okay, I’m very willing; what can I help you now?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "erdemcer/kafka-connect-oracle"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月17日(星期一) 下午3:47
收件人:&nbsp;"erdemcer/kafka-connect-oracle"<kafka-connect-oracle@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [erdemcer/kafka-connect-oracle]  java.sql.SQLException: ORA-01002: fetch out of sequence (#60)





 
Hi,
 It is  OJDBC7 and i suspected issue from cursors in stored procedures but after fixing it also getting same error,
 i know its commit issue which is default in jdbc, can you help us out to fix the above.
 Thank you.

**Comment by AvinashUrs** [comment]
I'm getting the same error in some situations "fetch out of sequence"  can you help me to fix this .

Thank you.

**Comment by AvinashUrs** [comment]
> Hi,
> Which jdbc driver are you using? version ? And is there any process on your db that can kill connector session which can be idle ?
> Thanks

Hi 
Any solution can I expect ? 

Thank you

**Comment by erdemcer** [comment]
Hi,
Could you please test this issue with new test release (kafka-connect-oracle-1.0.68_x.jar
) of this connector which can be downloaded from following url ?

https://github.com/erdemcer/kafka-connect-oracle/releases/tag/1.0.68_x
Thanks.

**Comment by AvinashUrs** [comment]
Hi 
Thanks for the release, will test and update you.
Thanks.

**Comment by fengant** [comment]
can you help me how to fix it?
Thanks

**Comment by leelizk** [comment]
anyone knows how to fix this issue?

**Comment by jintan502** [comment]
anyone knows how to fix this issue?
