### ISSUE TITLE
DBMS_LOGMNR.SKIP_CORRUPTION not declared

### ISSUE THREAD

**Issue by wangjunbo** [erdemcer/kafka-connect-oracle#7]
[2019-04-29 19:28:33,270] ERROR WorkerSourceTask{id=oracle-logminer-connector-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:172)
org.apache.kafka.connect.errors.ConnectException: Error at database tier, Please check : java.sql.SQLException: ORA-06550: 第 2 行, 第 54 列:
PLS-00201: 必须声明标识符 'DBMS_LOGMNR.SKIP_CORRUPTION'
ORA-06550: 第 2 行, 第 1 列:
PL/SQL: Statement ignored

	at com.ecer.kafka.connect.oracle.OracleSourceTask.start(OracleSourceTask.java:158)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:157)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:170)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:214)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

How to solve this problem ?

**Comment by yongorg** [comment]
Hi，
Have you solved this problem? thanks.

**Comment by wangjunbo** [comment]
No, I use ogg at last
