### ISSUE TITLE
archive log enabled but tip to enable it

### ISSUE THREAD

**Issue by ayida** [erdemcer/kafka-connect-oracle#75]
hi, sorry to disturb
i meet an problem , i enable the oracle11.2.0.1.0 archive log ,but when i start connector, error is `ORA-01325: archive log mode must be enabled to build into the logstream` ， ask for help ,thank you

archive log status:
```
SQL> archive log list
数据库日志模式            存档模式
自动存档             启用
存档终点            D:\app\Administrator\arch
最早的联机日志序列     876
下一个存档日志序列   878
当前日志序列           878
```

error log:
``` 
[2020-07-20 18:05:05,851] INFO Created connector healthcloud-connector (org.apache.kafka.connect.cli.ConnectStandalone:112)
[2020-07-20 18:05:05,852] INFO Oracle Kafka Connector is starting on orcl (com.ecer.kafka.connect.oracle.OracleSourceTask:110)
[2020-07-20 18:05:05,939] INFO [Producer clientId=connector-producer-healthcloud-connector-0] Cluster ID: 62nlJPU4Q6Ohrj5AxEYaXQ (org.apache.kafka.clients.Metadata:261)
[2020-07-20 18:05:06,607] INFO Connected to database version 112010 (com.ecer.kafka.connect.oracle.OracleSourceTask:115)
[2020-07-20 18:05:06,607] INFO Starting LogMiner Session (com.ecer.kafka.connect.oracle.OracleSourceTask:118)
[2020-07-20 18:05:06,636] INFO Resetting offset with new SCN (com.ecer.kafka.connect.oracle.OracleSourceTask:170)
[2020-07-20 18:05:06,662] INFO Getting current scn from database 3722420301 (com.ecer.kafka.connect.oracle.OracleSourceTask:185)
[2020-07-20 18:05:06,662] INFO Commit SCN : 0 (com.ecer.kafka.connect.oracle.OracleSourceTask:188)
[2020-07-20 18:05:06,662] INFO Log Miner will start at new position SCN : 3722420301 with fetch size : 1 (com.ecer.kafka.connect.oracle.OracleSourceTask:189)
[2020-07-20 18:05:06,706] INFO WorkerSourceTask{id=healthcloud-connector-0} Committing offsets (org.apache.kafka.connect.runtime.WorkerSourceTask:416)
[2020-07-20 18:05:06,707] INFO WorkerSourceTask{id=healthcloud-connector-0} flushing 0 outstanding messages for offset commit (org.apache.kafka.connect.runtime.WorkerSourceTask:433)
[2020-07-20 18:05:06,708] ERROR WorkerSourceTask{id=healthcloud-connector-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:179)
org.apache.kafka.connect.errors.ConnectException: Error at database tier, Please check : java.sql.SQLException: ORA-01325: archive log mode must be enabled to build into the logstream
ORA-06512: at "SYS.DBMS_LOGMNR", line 58
ORA-06512: at line 2

	at com.ecer.kafka.connect.oracle.OracleSourceTask.start(OracleSourceTask.java:220)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:208)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:177)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-07-20 18:05:06,710] ERROR WorkerSourceTask{id=healthcloud-connector-0} Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:180)
[2020-07-20 18:05:06,711] INFO Stop called for logminer (com.ecer.kafka.connect.oracle.OracleSourceTask:294)
[2020-07-20 18:05:06,711] INFO Logminer session cancel (com.ecer.kafka.connect.oracle.OracleSourceTask:297)
[2020-07-20 18:05:06,711] WARN Could not stop task (org.apache.kafka.connect.runtime.WorkerSourceTask:199)
java.lang.NullPointerException
	at com.ecer.kafka.connect.oracle.OracleSourceTask.stop(OracleSourceTask.java:298)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.tryStop(WorkerSourceTask.java:196)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.close(WorkerSourceTask.java:154)
	at org.apache.kafka.connect.runtime.WorkerTask.doClose(WorkerTask.java:156)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:183)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-07-20 18:05:06,712] INFO [Producer clientId=connector-producer-healthcloud-connector-0] Closing the Kafka producer with timeoutMillis = 30000 ms. (org.apache.kafka.clients.producer.KafkaProducer:1183)

```

**Comment by ayida** [comment]
i update this project from git and add some log.info  ,then  package to the server,  now i found the error point is `logMinerStartStmt.execute()` , when exexute the follow code
```
BEGIN
    SYS.DBMS_LOGMNR.START_LOGMNR(STARTSCN => ?,
                                 OPTIONS  => SYS.DBMS_LOGMNR.SKIP_CORRUPTION +
                                             SYS.DBMS_LOGMNR.NO_SQL_DELIMITER +
                                             SYS.DBMS_LOGMNR.NO_ROWID_IN_STMT +
                                             SYS.DBMS_LOGMNR.DICT_FROM_ONLINE_CATALOG +
                                             SYS.DBMS_LOGMNR.CONTINUOUS_MINE +
                                             SYS.DBMS_LOGMNR.COMMITTED_DATA_ONLY +
                                             SYS.DBMS_LOGMNR.STRING_LITERALS_IN_STMT);
END;
```

more detail error point is the option `SYS.DBMS_LOGMNR.CONTINUOUS_MINE`, i run the `START_LOGMNR` in plsql with `CONTINUOUS_MINE`，the error is `ora01325`, otherwise the error is `ora01292`
i

**Comment by ayida** [comment]
this question is solved，this is because there are two oracle database in one server , when i conn oracle like `conn / as sysdba`, i always operate the default db，when i realized , conn  like `conn aaa/bbb@cccc:ddd/orcl as sysdba`, archive log was not enabled, then the question is solved ^_^
thank you for your project~
