### ISSUE TITLE
If I do not have topic

### ISSUE THREAD

**Issue by Eric-zch** [erdemcer/kafka-connect-oracle#84]
I met the below errors when I did not specify the topic in OracleSourceConnector.properties

[2020-09-19 14:50:11,070] ERROR Stopping after connector error (org.apache.kafka.connect.cli.ConnectStandalone:121)
java.util.concurrent.ExecutionException: org.apache.kafka.connect.runtime.rest.errors.BadRequestException: Connector configuration is invalid and contains the following 1 error(s):
Missing required configuration "topic" which has no default value.
You can also find the above list of errors at the endpoint `/{connectorType}/config/validate`
        at org.apache.kafka.connect.util.ConvertingFutureCallback.result(ConvertingFutureCallback.java:115)
        at org.apache.kafka.connect.util.ConvertingFutureCallback.get(ConvertingFutureCallback.java:99)
        at org.apache.kafka.connect.cli.ConnectStandalone.main(ConnectStandalone.java:118)
Caused by: org.apache.kafka.connect.runtime.rest.errors.BadRequestException: Connector configuration is invalid and contains the following 1 error(s):
Missing required configuration "topic" which has no default value.
You can also find the above list of errors at the endpoint `/{connectorType}/config/validate`
        at org.apache.kafka.connect.runtime.AbstractHerder.maybeAddConfigErrors(AbstractHerder.java:560)
        at org.apache.kafka.connect.runtime.standalone.StandaloneHerder.putConnectorConfig(StandaloneHerder.java:194)
        at org.apache.kafka.connect.cli.ConnectStandalone.main(ConnectStandalone.java:115)

**Comment by Eric-zch** [comment]
![image](https://user-images.githubusercontent.com/67849191/93661591-83642d00-fa8b-11ea-8bbd-82e0812e8419.png)

Not sure if this function for creating topic dynamically is implemented or not.

**Comment by erdemcer** [comment]
Hi,
Could you please write topic configuration parameter into your properties file and leave it blank ? . Like this

topic=

Thanks.
